name: CI

on:
  push:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

  typecheck:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: npm run typecheck

  build:
    needs: typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: npm run build

  upload:
    needs: build
    runs-on: ubuntu-latest
    if: success() # ✅ Only run if build passed
    steps:
      - uses: actions/checkout@v4
      - name: Upload production-ready files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist # ✅ Correct folder for Vite builds
